# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomber < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/bomber"
  version "0.2.0"

  on_macos do
    url "https://github.com/devops-kung-fu/bomber/releases/download/v0.2.0/bomber_0.2.0_darwin_all.tar.gz"
    sha256 "9809fc5763005e65094ffc0f61c03e71b30a965a7799861755a3a71a911e092c"

    def install
      bin.install "bomber"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/bomber/releases/download/v0.2.0/bomber_0.2.0_linux_amd64.tar.gz"
      sha256 "58d95d38adcc376e385ddc6b60d62001f1ca3dfb5113450d3283710dcffde30f"

      def install
        bin.install "bomber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/bomber/releases/download/v0.2.0/bomber_0.2.0_linux_arm64.tar.gz"
      sha256 "e99d6b9afcc4a3a67222537785354a93ead994f718cfd4bf75bca02e384eec62"

      def install
        bin.install "bomber"
      end
    end
  end
end
