# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomber < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/bomber"
  version "0.5.1"

  on_macos do
    url "https://github.com/devops-kung-fu/bomber/releases/download/v0.5.1/bomber_0.5.1_darwin_all.tar.gz"
    sha256 "db1d99842333b8dde4f3a142feb5528dec2be01510c0b6d317764f8946ec5c40"

    def install
      bin.install "bomber"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devops-kung-fu/bomber/releases/download/v0.5.1/bomber_0.5.1_linux_amd64.tar.gz"
        sha256 "8f5c50072cb0a5d551b48da93d7608b49e47fbf16319be5f01cf6ef3c6019c4e"

        def install
          bin.install "bomber"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devops-kung-fu/bomber/releases/download/v0.5.1/bomber_0.5.1_linux_arm64.tar.gz"
        sha256 "118f713ea94e6270d311592b3c10a1f38cb455a7adc0392ce6c6662bf72d2061"

        def install
          bin.install "bomber"
        end
      end
    end
  end
end
