# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomber < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/bomber"
  version "0.4.7"

  on_macos do
    url "https://github.com/devops-kung-fu/bomber/releases/download/v0.4.7/bomber_0.4.7_darwin_all.tar.gz"
    sha256 "b839a82f272343981ec4f70e03a682fe2da57202bae4759c6aa67a7c57205873"

    def install
      bin.install "bomber"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/bomber/releases/download/v0.4.7/bomber_0.4.7_linux_arm64.tar.gz"
      sha256 "40cfb1c9d4d39c192a6a8cf342ac00496f97ffba7482fcb2e36991ca1cec30b6"

      def install
        bin.install "bomber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/bomber/releases/download/v0.4.7/bomber_0.4.7_linux_amd64.tar.gz"
      sha256 "71f15a37145882702dd599202154d1d5f5d12429ad9cc552c8360362b6fd87fc"

      def install
        bin.install "bomber"
      end
    end
  end
end
