# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gardener < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/gardener"
  version "1.0.1"

  on_macos do
    url "https://github.com/devops-kung-fu/gardener/releases/download/v1.0.1/gardener_1.0.1_darwin_all.tar.gz"
    sha256 "3bac82c9aeedc029b86f77a6ea20b1895e82de01f4ea2531b531e05056412a9e"

    def install
      bin.install "gardener"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/gardener/releases/download/v1.0.1/gardener_1.0.1_linux_arm64.tar.gz"
      sha256 "529c0ee93223d478c6e7f953d227ec471f648d6b9e4858f491d08d11fc4696d0"

      def install
        bin.install "gardener"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/gardener/releases/download/v1.0.1/gardener_1.0.1_linux_amd64.tar.gz"
      sha256 "9259081a4f8dcba5ddc8dae9fb884cf0249276c69ec37941848d8bdb5b0e5c55"

      def install
        bin.install "gardener"
      end
    end
  end
end
