# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hinge < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/hinge"
  version "1.0.1"

  on_macos do
    url "https://github.com/devops-kung-fu/hinge/releases/download/v1.0.1/hinge_1.0.1_darwin_all.tar.gz"
    sha256 "587279d74ff852ebe40d65e5e298b35802917691bc16b61307c92b23d1eec27a"

    def install
      bin.install "hinge"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/hinge/releases/download/v1.0.1/hinge_1.0.1_linux_arm64.tar.gz"
      sha256 "cc048285f2ed1df918a6b971f631b6cbd57391f3e1a1ab30574dd5a557cc1d64"

      def install
        bin.install "hinge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/hinge/releases/download/v1.0.1/hinge_1.0.1_linux_amd64.tar.gz"
      sha256 "60c3dd71135d675d685e54208938b4ec50fdac8bde4f9e315a7d4104cc584813"

      def install
        bin.install "hinge"
      end
    end
  end
end
