# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookz < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/hooks"
  version "2.4.4"

  on_macos do
    url "https://github.com/devops-kung-fu/hookz/releases/download/v2.4.4/hookz_2.4.4_darwin_all.tar.gz"
    sha256 "14c255a79185bf5582a89a0b8481b262500797fc30667c89f02877550aea1f54"

    def install
      bin.install "hookz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/hookz/releases/download/v2.4.4/hookz_2.4.4_linux_arm64.tar.gz"
      sha256 "3770fd6fc69769a9b49bb62297e05b3eeb126382e524d0d0458e4994de4dd2fe"

      def install
        bin.install "hookz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/hookz/releases/download/v2.4.4/hookz_2.4.4_linux_amd64.tar.gz"
      sha256 "ad881fc06a306110e18dfa92339c4160ff3a1d02732411b528d021780abe10c6"

      def install
        bin.install "hookz"
      end
    end
  end
end
