# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hookz < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/hooks"
  version "2.4.1"

  on_macos do
    url "https://github.com/devops-kung-fu/hookz/releases/download/v2.4.1/hookz_2.4.1_darwin_all.tar.gz"
    sha256 "ca8e715bb58e7aaf9dc9b9064be4b32143e51ec52ddd2b04bfd0e105c81a1e2f"

    def install
      bin.install "hookz"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/hookz/releases/download/v2.4.1/hookz_2.4.1_linux_arm64.tar.gz"
      sha256 "1967b19e775819fafcfd0bdc89b71f637ec4fb71e7f1c301ea644ff66c68276f"

      def install
        bin.install "hookz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/hookz/releases/download/v2.4.1/hookz_2.4.1_linux_amd64.tar.gz"
      sha256 "cf2414dbc7208f7f0a0ce67057244eaf754460771004eeb3a79610638ffd9324"

      def install
        bin.install "hookz"
      end
    end
  end
end
