# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kissbom < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/kissbom"
  version "0.0.2"

  on_macos do
    url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_darwin_all.tar.gz"
    sha256 "2406f8a8678ff25d4a638e2b3d5d10da86ad43ab926bf06a97e942bd8988b5bb"

    def install
      bin.install "kissbom"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_linux_arm64.tar.gz"
      sha256 "42003c07ddc8f73f853ec2379f274a9e9352e8a745b298ab297ea63e53fcce9c"

      def install
        bin.install "kissbom"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_linux_amd64.tar.gz"
      sha256 "59ccb8b6589051b99d4a29282ab55071235f8398582a0eca473079f504ff1550"

      def install
        bin.install "kissbom"
      end
    end
  end
end
