# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kissbom < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/kissbom"
  version "0.0.2"

  on_macos do
    url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_darwin_all.tar.gz"
    sha256 "bad07a29e9fb5f8a86123d98d42256ff5de6284e50e1070f101bfabaeee517b0"

    def install
      bin.install "kissbom"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_linux_arm64.tar.gz"
      sha256 "9d978ade1b34d547969ef231c32ecb473b10e5232d52a23e60ce70cabc893717"

      def install
        bin.install "kissbom"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_linux_amd64.tar.gz"
      sha256 "c75bd7c9dae3277380ca5e8414fccb2f05a0a369b80378b131ebe514ec2f114d"

      def install
        bin.install "kissbom"
      end
    end
  end
end
