# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kissbom < Formula
  desc ""
  homepage "https://github.com/devops-kung-fu/kissbom"
  version "0.0.2"

  on_macos do
    url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_darwin_all.tar.gz"
    sha256 "f1e8e357b8752693d6448316165e6ce99e40db185cf02ff683f666de313aa957"

    def install
      bin.install "kissbom"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_linux_arm64.tar.gz"
      sha256 "54c26dd8050ae89bd008a25bff01c731d03a5a4552e9cf37ce7fa64adca8b384"

      def install
        bin.install "kissbom"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devops-kung-fu/kissbom/releases/download/v0.0.2/kissbom_0.0.2_linux_amd64.tar.gz"
      sha256 "ada1c3f8c0ed257e446374dbf5478942eb6756dc1e25e5c908ec9abb41fc589e"

      def install
        bin.install "kissbom"
      end
    end
  end
end
